[package]
name = "fmo_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1"
axum = { version = "0.7.5", features = ["json"] }
chrono = { version = "0.4.38", features = ["serde"] }
deadpool-postgres = "0.14.0"
esplora-client = { version = "0.10.0", default-features = false, features = [
    "async-https-rustls",
] }
fedimint-api-client = { workspace = true }
fedimint-connectors = { workspace = true }
fedimint-core = { workspace = true }
fedimint-meta-client = { workspace = true }
fmo_api_types = { path = "../fmo_api_types" }
futures = "0.3.30"
hex = "0.4.3"
nostr-sdk = "0.34.0"
postgres-from-row = "0.5.2"
regex = "1.10.4"
reqwest = { version = "0.12.2", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["full"] }
tokio-postgres = { version = "0.7.11", features = [
    "with-chrono-0_4",
    "with-serde_json-1",
] }
tracing = "0.1.40"

[dev-dependencies]
fedimint-dummy-common = { version = "0.10.0", git = "https://github.com/fedimint/fedimint", tag = "v0.10.0" }
