[workspace]
members = [
    "fmo_api_types",
    "fmo_core",
    "fmo_modules/fmo_module_mint",
    "fmo_modules/fmo_module_mintv2",
    "fmo_modules/fmo_module_wallet",
    "fmo_modules/fmo_module_walletv2",
    "fmo_modules/fmo_module_ln",
    "fmo_modules/fmo_module_lnv2",
    "fmo_server",
]

resolver = "2"

[workspace.dependencies]
fedimint-api-client = { version = "0.11.1", git = "https://github.com/fedimint/fedimint", tag = "v0.11.1" }
fedimint-connectors = { version = "0.11.1", git = "https://github.com/fedimint/fedimint", tag = "v0.11.1" }
fedimint-core = { version = "0.11.1", git = "https://github.com/fedimint/fedimint", tag = "v0.11.1" }
fedimint-ln-common = { version = "0.11.1", git = "https://github.com/fedimint/fedimint", tag = "v0.11.1" }
fedimint-lnv2-common = { version = "0.11.1", git = "https://github.com/fedimint/fedimint", tag = "v0.11.1" }
fedimint-meta-client = { version = "0.11.1", git = "https://github.com/fedimint/fedimint", tag = "v0.11.1" }
fedimint-mint-common = { version = "0.11.1", git = "https://github.com/fedimint/fedimint", tag = "v0.11.1" }
fedimint-mintv2-common = { version = "0.11.1", git = "https://github.com/fedimint/fedimint", tag = "v0.11.1" }
fedimint-wallet-common = { version = "0.11.1", git = "https://github.com/fedimint/fedimint", tag = "v0.11.1" }
fedimint-walletv2-common = { version = "0.11.1", git = "https://github.com/fedimint/fedimint", tag = "v0.11.1" }
